"""Fix User and Plan relationship annotations

Revision ID: d8b73c03b81c
Revises: bdd118983d84
Create Date: 2025-06-07 11:42:26.709125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b73c03b81c'
down_revision: Union[str, None] = 'bdd118983d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'enable_ai_fine_tune')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('enable_ai_fine_tune', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
