"""fix plan-user relationship

Revision ID: 8c405618f0d9
Revises: d8b73c03b81c
Create Date: 2025-06-07 11:52:54.774630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c405618f0d9'
down_revision: Union[str, None] = 'd8b73c03b81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No schema changes required for this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No schema changes to revert for this migration.
    # ### end Alembic commands ###
